### ISSUE TITLE
what is the status?

### ISSUE THREAD

**Issue by dgreisen-cfpb** [cfpb/jenkins-automation#6]
Hey @imuchnik @Ooblioob. Glad to see continued development! I'm getting ready to set up a CI pipeline and was wondering whether the project is in a state that I can use it? Should I work off the ooblioob fork, or should I stick with the master? Has config changed? Have things settled down with development, or are you finding lots of things you still need to break?

I also saw that you started building some wrappers. Are those jobdsl extensions?

**Comment by imuchnik** [comment]
@dgreisen-cfpb !!!! What a nice surprise! Yes, there is active development on it and there are changes and new wrapper. I just came back from a vacation, so @Ooblioob  will write up a more detailed response, but in a nutshell while standing on one leg
- We are also going to contribute back to the main project in the way of adding support for Saucelabs, rather than writing an extension.
- The are util wrappers for multiscm block ( an easy example to follow should you want to write more)
- We simplified the flow a bit

![selfie-0](http://i.imgur.com/HAoefij.gif)

**Comment by Ooblioob** [comment]
hey @dgreisen-cfpb, hope you're doing well!  

Yes, we're still doing active development, though there have been some changes as we started gearing up for adoption by teams.  @imuchnik has contributed a very nice SauceLabs plugin to the job dsl plugin, and we've got a new wrapper for the multi-scm block that looks something like this:

```
job("some-job-name") {
    using 'template-base'
    multiscm {
        ScmUtils.project_repos(delegate, urls)
    }
}
```

The idea is that urls is a list of urls to include, and could either be populated manually (i.e. `def urls = ['...', '...']`) at the top of the file or programmatically using `getRepositoryUrls()` like so:

```
urls = repoParser.getRepositoryUrls(this, 'repo-name-that-has-repositories-yml-file')
```

The decision here was lower the barrier for adoption.  Teams could get up and running right away by plugging in their urls at the top of the file.  Downside is it's less pretty and create yet another place to store repo names and version, so as a team matures we'd like to see the creation of that `repositories.yml` file.  

Also, since we have this wrapper for our projects, we no longer need the concept of a workspace builder or separate trigger jobs, which greatly reduces the complexity of our tools!  :)  One area that we still need to sort out is extracting the correct version from the urls in the wrapper, but that shouldn't be too bad.  FYI @imuchnik 

Another key decision, at least for now, is to ask teams to manually create their own seed jobs rather than utilize the flow we discussed with `job-dsl-master` and `job-dsl-project-builder`.  We did some user testing (literally ambushing colleagues and trying to explain this process to them), and it became abundantly clear that when we introduced lots of new concepts to them (jobs that create jobs, groovy dsl, etc) they couldn't keep the job-dsl-master workflow straight.  In the end, teams understood it far better when we explained it using just the seed job as the starting point, so at least for now we're going to focus on that.  The downside is that for each Jenkins environment each team will have to create a separate seed job manually, but at the moment that's a reasonable amount of technical debt to bear.  In the future, as teams get more familiar with the process, we can reintroduce job-dsl-master.  

For now, current plan is to build out some more templates for our common jobs.  If you're looking for the bleeding edge with the new templates, go ahead and grab a copy from the Ooblioob fork, but I haven't pushed it to CFPB yet because we changed quite a bit and we need to make sure it works first.  

Let me know if all that makes sense.

**Comment by dgreisen-cfpb** [comment]
Thanks for the info. Sorry for the delayed response. Apparently I'm not getting emails when there are responses to my comments. That's frustrating. I spent a half a day trying to get the system up and running, but I've decided that it's a bit of premature optimization, considering it's only myself at the moment.

I'm glad things are progressing, and I'll be excited to see where they end up.

**Comment by imuchnik** [comment]
@dgreisen-cfpb To get what we have in right now working, you need our super special version of the plugin. Or wait until [this](https://github.com/jenkinsci/job-dsl-plugin/pull/624) is merged.
